//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSProjectManager_GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSProjectManager_GUI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutWinodw {
            get {
                return ResourceManager.GetString("AboutWinodw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add File 的本地化字符串。
        /// </summary>
        public static string AddFileButtonText {
            get {
                return ResourceManager.GetString("AddFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File 的本地化字符串。
        /// </summary>
        public static string CheckBox_SavePathText {
            get {
                return ResourceManager.GetString("CheckBox_SavePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean All 的本地化字符串。
        /// </summary>
        public static string CleanAllButtonText {
            get {
                return ResourceManager.GetString("CleanAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Del File 的本地化字符串。
        /// </summary>
        public static string DelFileButtonText {
            get {
                return ResourceManager.GetString("DelFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 input path 的本地化字符串。
        /// </summary>
        public static string InputFileButtonText {
            get {
                return ResourceManager.GetString("InputFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add File List 的本地化字符串。
        /// </summary>
        public static string InputFileListText {
            get {
                return ResourceManager.GetString("InputFileListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter complete paths, one per line, or drag and drop files here. 的本地化字符串。
        /// </summary>
        public static string InputFileListTip {
            get {
                return ResourceManager.GetString("InputFileListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input file path 的本地化字符串。
        /// </summary>
        public static string InputfilepathWindow {
            get {
                return ResourceManager.GetString("InputfilepathWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Label_AboutText {
            get {
                return ResourceManager.GetString("Label_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is used to generate the projects.json file for the Project Manager of the VScode extension, enabling automatic addition of file tags and paths. 的本地化字符串。
        /// </summary>
        public static string Label_AboutTextTips {
            get {
                return ResourceManager.GetString("Label_AboutTextTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config File 的本地化字符串。
        /// </summary>
        public static string Label_ConfigFile {
            get {
                return ResourceManager.GetString("Label_ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select tags (multiple choices are allowed) 的本地化字符串。
        /// </summary>
        public static string Label_SelectTagslistText {
            get {
                return ResourceManager.GetString("Label_SelectTagslistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        public static string Label_TagsText {
            get {
                return ResourceManager.GetString("Label_TagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Lang_About2 {
            get {
                return ResourceManager.GetString("Lang_About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        public static string Lang_Simplified {
            get {
                return ResourceManager.GetString("Lang_Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese 的本地化字符串。
        /// </summary>
        public static string Lang_Traditional {
            get {
                return ResourceManager.GetString("Lang_Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        public static string Menu_Export_Backup {
            get {
                return ResourceManager.GetString("Menu_Export_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Menu_Export_title {
            get {
                return ResourceManager.GetString("Menu_Export_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export TXT list 的本地化字符串。
        /// </summary>
        public static string Menu_Export_txt {
            get {
                return ResourceManager.GetString("Menu_Export_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension Link 的本地化字符串。
        /// </summary>
        public static string Menu_ExtensionLink {
            get {
                return ResourceManager.GetString("Menu_ExtensionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Menu_Theme {
            get {
                return ResourceManager.GetString("Menu_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Menu_ThemeDark {
            get {
                return ResourceManager.GetString("Menu_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Menu_ThemeLight {
            get {
                return ResourceManager.GetString("Menu_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup failure: 的本地化字符串。
        /// </summary>
        public static string Msg_BackupFailed {
            get {
                return ResourceManager.GetString("Msg_BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup successful! File saved in: 的本地化字符串。
        /// </summary>
        public static string Msg_BackupSuccess {
            get {
                return ResourceManager.GetString("Msg_BackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export failure: 的本地化字符串。
        /// </summary>
        public static string Msg_ExportFailed {
            get {
                return ResourceManager.GetString("Msg_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export success! The file is exported in: 的本地化字符串。
        /// </summary>
        public static string Msg_ExportSuccess {
            get {
                return ResourceManager.GetString("Msg_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON file parsing failed. 的本地化字符串。
        /// </summary>
        public static string Msg_JSONfileparsingfailed {
            get {
                return ResourceManager.GetString("Msg_JSONfileparsingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list is empty. Please add files. 的本地化字符串。
        /// </summary>
        public static string Msg_listempty {
            get {
                return ResourceManager.GetString("Msg_listempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No configuration file selected 的本地化字符串。
        /// </summary>
        public static string Msg_Noconfigfileselected {
            get {
                return ResourceManager.GetString("Msg_Noconfigfileselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No input content. 的本地化字符串。
        /// </summary>
        public static string Msg_NoInputContent {
            get {
                return ResourceManager.GetString("Msg_NoInputContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0} files,Added {1} files,Skipped {2} duplicate files. 的本地化字符串。
        /// </summary>
        public static string Msg_ProjectResult {
            get {
                return ResourceManager.GetString("Msg_ProjectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Please select a valid JSON file first. 的本地化字符串。
        /// </summary>
        public static string Msg_SelectvalidJSONfile {
            get {
                return ResourceManager.GetString("Msg_SelectvalidJSONfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No tags were found in JSON. 的本地化字符串。
        /// </summary>
        public static string Msg_Therenotags {
            get {
                return ResourceManager.GetString("Msg_Therenotags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi-label example：Note1,Note2,Note3 的本地化字符串。
        /// </summary>
        public static string Multilabeleg {
            get {
                return ResourceManager.GetString("Multilabeleg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OKbutton {
            get {
                return ResourceManager.GetString("OKbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string OpenFileButton {
            get {
                return ResourceManager.GetString("OpenFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open projects.json File 的本地化字符串。
        /// </summary>
        public static string Openprojectsjsontxt {
            get {
                return ResourceManager.GetString("Openprojectsjsontxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate JSON file 的本地化字符串。
        /// </summary>
        public static string OutJSONButtonText {
            get {
                return ResourceManager.GetString("OutJSONButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags List 的本地化字符串。
        /// </summary>
        public static string TagsButtonText {
            get {
                return ResourceManager.GetString("TagsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags Select Window 的本地化字符串。
        /// </summary>
        public static string TagsSelectWindow {
            get {
                return ResourceManager.GetString("TagsSelectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose to save the JSON file 的本地化字符串。
        /// </summary>
        public static string Title_ChooseSaveJSONfile {
            get {
                return ResourceManager.GetString("Title_ChooseSaveJSONfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export TXT list 的本地化字符串。
        /// </summary>
        public static string Title_ExportTXTlIST_Filesave {
            get {
                return ResourceManager.GetString("Title_ExportTXTlIST_Filesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File 的本地化字符串。
        /// </summary>
        public static string Title_Selectfile {
            get {
                return ResourceManager.GetString("Title_Selectfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select projects.json File 的本地化字符串。
        /// </summary>
        public static string Title_Selectprojectsfile {
            get {
                return ResourceManager.GetString("Title_Selectprojectsfile", resourceCulture);
            }
        }
    }
}
